name: Build Electron App
on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron App for Windows
        run: npm run electron:build:win

      - name: Upload Production Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Electron-App-Windows
          path: release/*.exe
          if-no-files-found: error
